<html>
<center>
    <h1>Login</h1>
    <?php echo $this->escapeHtml($this->messages); ?>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('myauth', array('controller' => 'index', 'action' => 'login')));
    $form->prepare();

    echo $this->form()->openTag($form);

    ?>

    <table cellpadding="10" width="20%">
        <tr>
            <td> Email</td>
            <td><?php echo $this->formRow($form->get('usr_email')); ?></td>

        </tr>
        <td>Пароль</td>
        <td><?php echo $this->formRow($form->get('usr_password')); ?></td>
        </tr>

    </table>
    <br>

    <?php
    echo $this->formRow($form->get('rememberme'));
    echo "<br><br>";
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>


    <br><br>
    <?php // view helper
    if ($user = $this->identity()) {
        echo 'Logged in as ' . $this->escapeHtml($user->usr_name);
        ?>
        <meta http-equiv=Refresh content="0; url=/zend/anket/anket/user">
        | <a
            href="<?php echo $this->url('myauth', array('controller' => 'index', 'action' => 'logout')); ?>"><?php echo $this->translate('Выйти'); ?></a>
        <?php
    } else {
        echo 'Not logged in';
    }
    ?>
    <br>

    <p>
        <a href="<?php echo $this->url('myauth', array('controller' => 'registration', 'action' => 'index')); ?>"><?php echo $this->translate('Регистрация'); ?></a>

    </p>
</center>
</html>