<?php
switch ($type) {
    case 1:
        $title = 'Анкета 1';
        break;
    case 2:
        $title = 'Анкета 2';
        break;
    case 3:
        $title = 'Анкета 3';
        break;
    case 4:
        $title = 'Анкета 4';
        break;
}
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('anket', array('controller' => 'anket', 'action' => 'add', 'page' => '1', 'type' => $type)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('name_anket'));
?>
<table cellpadding="10" width="70%">
    <tr>
        <td> Ф.И.О</td>
        <td><?php echo $this->formRow($form->get('name')); ?></td>
    </tr>
    <td>Тефон</td>
    <td><?php echo $this->formRow($form->get('phone')); ?></td>
    </tr>
    <td>E-mail</td>
    <td><?php
        if ($user = $this->identity()) {
            echo $this->formRow($form->get('email')->setValue($user->usr_email));
        } else {
            echo $this->formRow($form->get('email'));
        }
        ?></td>
    </tr>
    <td>Вид оборудования</td>
    <td><?php echo $this->formRow($form->get('type_equipment')); ?></td>
    </tr>
    <td></td>
    <td>
        <?php echo $this->formRow($form->get('call_back')); ?> Перезвонить мне
    </td>
    </tr>
    <td>Ваш коментарий</td>
    <td><?php echo $this->formRow($form->get('comments')); ?></td>
    </tr>
</table>
<br/><br/>
<?php
echo $this->formRow($form->get('captcha'));
echo '<br/><br/>';
echo $this->formRow($form->get('send_mail'));
echo '  Отправить заполненную форму на Email';
echo '<br/><br/>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<br><br>
<?php // view helper
if ($user = $this->identity()) {
    echo 'Logged in as ' . $this->escapeHtml($user->usr_name);
    ?>
    | <a
        href="<?php echo $this->url('myauth', array('controller' => 'index', 'action' => 'logout')); ?>"><?php echo $this->translate('Выйти'); ?></a>
    <?php
} else {
    echo 'Not logged in';
}
?>
