<?php
$title = 'Редактор анкеты';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('anket', array('controller' => 'anket', 'action' => 'edit', 'id' => $this->id)));
$form->prepare();
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formHidden($form->get('name_anket')) . PHP_EOL;
?>

    <table cellpadding="10" width="30%">
        <tr>
            <td> Ф.И.О</td>
            <td><?php echo $this->formRow($form->get('name')) . PHP_EOL; ?></td>
        </tr>
        <td>Тефон</td>
        <td><?php echo $this->formRow($form->get('phone')) . PHP_EOL; ?></td>
        </tr>
        <td>E-mail</td>
        <td><?php echo $this->formRow($form->get('email')) . PHP_EOL; ?></td>
        </tr>
        <td>Вид оборудования</td>
        <td><?php echo $this->formRow($form->get('type_equipment')) . PHP_EOL; ?></td>
        </tr>
        <td></td>
        <td>
            <?php echo $this->formRow($form->get('call_back')) . PHP_EOL; ?> Перезвонить мне
        </td>
        </tr>
        <td>Ваш коментарий</td>
        <td><?php echo $this->formRow($form->get('comments')) . PHP_EOL; ?></td>
        </tr>

    </table>
    <br/><br/>
<?php
echo $this->formRow($form->get('captcha')) . PHP_EOL;
echo '<br/><br/>';
echo $this->formRow($form->get('send_mail')) . PHP_EOL;
echo '  Отправить заполненную форму на Email';
echo '<br/><br/>';
echo $this->formSubmit($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag() . PHP_EOL;
?>