<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <!--<ul> -->
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('anket', array('controller'=> 'anket','page' => $this->first, 'type'=>$type, 'order_by' => $order_by, 'order' => $order,)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('anket', array('controller'=> 'anket','page' => $this->previous, 'type'=>$type, 'order_by' => $order_by, 'order' => $order,)); ?>">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('anket', array('controller'=> 'anket','page' => $page, 'type'=>$type,'order_by' => $order_by, 'order' => $order,)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('anket', array('controller'=> 'anket','page' => $this->next, 'type'=>$type, 'order_by' => $order_by, 'order' => $order,)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('anket', array( 'controller'=> 'anket','page' => $this->last, 'type'=>$type, 'order_by' => $order_by, 'order' => $order,)); ?>">&raquo;</a></li>
        <!--</ul>-->
    </div>
<?php endif; ?>